appVersion: 1.0.0
metadata:
  isMaster: False
  uid: 0
  name: none
cluster:
  mainTable: none # The largest/most visited table's name
  maxTables: 18   # The capacity for tables
  neighbor: 0     # One of its neighbor's uid
network:
  timeOut: 3000
  recvPort: 2333
zookeeper:
  ip: 127.0.0.1
  port: 2181
