appVersion: 1.0.0
metadata:
  isMaster: False
  uid: 0
  name: master
cluster:
  mainTable: none # The largest/most visited table's name
  maxTables: 18   # The capacity for tables
  neighbor: 0     # One of its neighbor's uid
network:
  ip: 127.0.0.1
  timeOut: 3000
  rpcPort: 9092
  socketPort: 9093
zookeeper:
  ip: 127.0.0.1
  port: 2181

